import React from 'react';
import PropTypes from 'prop-types';
import "./index.scss";
import {  Grid, Row, Col } from 'react-bootstrap';

class Terms extends React.Component {
  render() {
    return (
      <Grid>
        <Row>
          <h3>Bus ticket reservation - Terms and Conditions </h3>
          <p > These terms and conditions (collectively, hereinafter referred to as the <strong>"Terms"</strong>) govern your (<strong>"User"</strong>) access to and use of the website, www.digitalbihar.com and the digital bihar mobile applications (<strong>"Website"</strong>). The Website is owned, managed and operated by <strong>DigitalBihar</strong>. </p>
          <p> Please read these Terms carefully before using the Website, which is an online marketplace. For the purpose of clarity, it is hereby stated that the Website is not engaged in providing any services by itself but is a platform, which merely connects the bus operators with the bus travellers.</p>
          <p > These Terms are an electronic record in terms of the applicable legislation. This electronic record is generated by a computer system and does not require any physical or digital signatures. By using the Website, you signify your agreement to be bound by these Terms. </p>
          <p > digital bihar allows You to surf the Website or buy bus tickets for yourself, your family and your friends, without registering on the Website. You shall be deemed to have read, understood and expressly accepted these Terms, which shall govern the desired transaction of bus ticket booking through the Website for all purposes, and shall be binding on You. All Your rights and liabilities and/or the Website with respect to Your use of the Website and availing bus ticket booking facility ("Facility") provided by the Website shall be governed by these Terms. </p>
          <p > PLEASE NOTE THAT YOUR USE OF THE WEBSITE IN ANY WAY SIGNIFIES YOUR ACCEPTANCE TO THE TERMS. By agreeing to these Terms, You also agree to digital bihar' other Website policies; including but not limited to, (i) Privacy Policy, as amended from time to time; and (ii) Cookie Policy. </p>
          <p > In addition to these Terms, any other ‘terms of service’ of the application-programming interface (<strong>“API”</strong>) with which digital bihar may tie-up would form an integral part of these Terms (hereinafter referred to as the <strong>“API Terms”</strong>). However, in the event of a conflict between such API Terms and these Terms, these Terms provided herein shall prevail. </p>
          <p > Both You and digital bihar are individually referred to as 'Party' and collective referred to as 'Parties', in these Terms.</p>
          <ol>
              <li> <strong>Terminology:</strong>
                  <ol>
                      <li> For the purpose of these Terms, wherever the context so requires "You" or "User" (would mean 'digital bihar user') shall mean any natural or legal person who has agreed to become a buyer of the bus tickets and/or an availer of the Facility being offered on the Website. </li>
                      <li> The term "We", "Us", "Our" shall mean digital bihar and/or its affiliates. </li>
                  </ol>
              </li>
              <li> <strong>Our Website:</strong>
                  <p> digital bihar is an online Market Place, which gives prospective travelers and bus operators a platform to connect. In light of the foregoing, digital bihar wishes to state the following: </p>
                  <ol>
                      <li> The Website is a marketplace, which merely lists the inventory of bus operators who are registered with the Website, but does not own the services per se. Hence, the limited role of the Website is to connect You with the bus operator and vice versa.</li>
                      <li> You understand and agree that the fare of the bus tickets listed and/or offered for sale by the bus operator on the Website, is solely determined by the respective bus operator, and digital bihar has no control over the fare of the tickets listed on the Website. In the event, the minimum and/or the maximum fare of the tickets, is in contravention of any law and/or any order or judgment of any regulatory authority/Tribunal/Court, it shall be the sole responsibility of the respective bus operator to ensure that such fare is in compliance with the law/order/judgment, and digital bihar shall in no way be liable for such contravention of the law/order/judgment. </li>
                      <li> In light of the foregoing, You agree that any liability in relation to any services being offered on the Website in accordance with the applicable laws shall be that of the bus operator and not digital bihar. In case of any deficiency of service, You agree to pursue any such action arising from such deficiency of service against the bus operator and not the digital bihar.</li>
                      <li> You further agree and acknowledge that the digital bihar is only a facilitator and is not and cannot be a party to or control in any manner any transactions on the Website. Accordingly, the contract of sale of services on the Website shall be a strictly bipartite contract between You and the bus operators listed on the Website. </li>
                      <li> You further agree and acknowledge that all the 'discounts/coupons (if any)' on the Website/prices at which the tickets are being sold by the bus operator on the Website is merely an “invitation to offer” in accordance with the applicable law and shall not be construed to be an “offer” in accordance with the applicable law. Hence, in light of the foregoing, when you agree to purchase the bus tickets listed on the Website by the bus operator, that would be termed as a 'valid offer' under the applicable law Subsequently, when the same is being confirmed by the bus operator it tantamount to be a 'valid contract' as per the applicable law. </li>
                  </ol>
              </li>
              <li> <strong>User Account:</strong>
                  <p> digital bihar may offer You the facility of opening user account on the Website. This user account can be linked to the Your email-id or phone number or both. For Your use of the Website, either by registering an account with digital bihar or using the Website as a guest (unregistered user), You agree to the following: </p>
                  <ol>
                      <li> You are solely responsible for maintaining the confidentiality of Your account and password and for restricting access to Your device to prevent unauthorized access to Your account when You use the Website by registering an account with digital bihar. </li>
                      <li> By using the Website, either as a guest user or registered user, You authorize digital bihar and its agents to access third party sites, including but not limited to that of banks and other payment gateways, designated by the bank or on the bank's behalf for retrieving requested information for processing of a customer generated transaction on the Website. </li>
                      <li> In the event that You use the Website through a registered account, You agree to accept responsibility for all activities that occur through your digital bihar account. </li>
                      <li> In the event that You use the Website through a registered account, You should take all necessary steps to ensure that the password is kept confidential and secure and should inform digital bihar immediately if You have any reason to believe that Your password has been compromised, or if the password is being, or is likely to be, used in an unauthorized manner. digital bihar shall not be liable for any losses You may incur owing to any compromised login credentials of Your digital bihar account. Please ensure that the details You provide digital bihar are correct, complete and up to date and inform digital bihar immediately of any changes to the information that You provide at the time of registering Your account with digital bihar. </li>
                      <li>digital bihar will not be responsible for screening, censoring or otherwise controlling transactions, including ascertaining whether the transaction is legal and valid as per the laws of the land, if you are resident/national of a country other than India. </li>
                      <li> You warrant that You will abide by all such additional procedures and guidelines, as modified from time to time, in connection with Your use of Website. You shall also be liable to comply with all applicable laws and regulations regarding use of the Website with respect to the jurisdiction concerned for each transaction. </li>
                      <li> Website may be used for Your personal and non-commercial purposes only. Therefore, You are not allowed to re-sell, deep-link, use, copy, monitor (e.g. spider, scrape), display, download or reproduce any content or information, software, products or Facility available on Website for any commercial or competitive activity/purpose. </li>
                      <li> digital bihar reserves the right to refuse Your access to Website, terminate Your digital bihar account, cancel any bus ticket reservations, remove and/or edit content on the Website at any time without notice if we have reasonable belief that Your account is being used for purposes other than as defined under Clause 3(7). </li>
                  </ol>
              </li>
              <li> <strong>Membership Eligibility:</strong>
                  <ol>
                      <li> Use of the Website is available only to persons who can enter into legally binding contracts under the applicable law. Persons who are "incompetent to contract" within the meaning of the applicable law are not eligible to use the Website. If You are a minor, you shall not register as a User of the Website and shall not transact on or use the Website. </li>
                      <li> As a minor if You wish to use or transact on the Website, such use or transaction may be made by Your legal guardian or parents. We reserve the right to terminate Your membership and/or refuse to provide You with access to the Website if it is discovered that You are a minor or incompetent to contract according to the law. </li>
                  </ol>
              </li>
              <li> <strong>digital bihar Wallet:</strong>
                  <p>digital bihar may provide at its sole discretion, the facility to transact through an online digital bihar wallet (<strong>"Wallet"</strong>) to its registered users with the following features:</p>
                  <ol>
                      <li> Upon cancellation of previously booked tickets, you would be accorded an option of either withdrawing such amounts to your bank account/credit card linked to the account or to the Wallet.</li>
                      <li> The cash equivalent balance available in the Wallet may be used by the Customer for making bus ticket bookings or Hotel bookings or avail any other services available at www.digital bihar.in (Website) and digital bihar Mobile Application only.</li>
                      <li> The present form and format of the Wallet, issued by digital bihar to its Customers, is modelled on a closed system prepaid payment instrument.</li>
                      <li> Any promotional cash credited in to your Wallet by digital bihar, will not be refundable into your bank account under any circumstances. On cancellation of a reservation of services provided by digital bihar, any utilised promotional cash will be forfeited. This promotional cash has an expiry date beyond which, it will not be available for your usage.</li>
                      <li> The customers are advised to use the amount lying in the Wallet within its validity period. Any amount lying unutilised (except promotional cash deposited by digital bihar) beyond a period of three hundred and sixty-five days shall be deemed to be held in trust with the Company. It will be held in trust for a maximum period of one year, after which digital bihar will make reasonable efforts to transfer such amount to the beneficiary and if such transfer is not an option, any unclaimed amount will be forfeited. </li>
                      <li> Maximum of 10% of the ticket price can be availed from the wallet promotional cash for ticket booking. digital bihar reserves the right to modify such percentage at its sole discretion without any prior intimation.</li>
                      <li> The amount lying in the Wallet are not transferable to any other Wallet of same or different user.</li>
                      <li> The option of keeping the refund amount in Wallet is available only to resident Indians only. Also the amount lying in the Wallets are not available for transactions in foreign currency.</li>
                      <li> By choosing the option to maintain the Wallet with the Company, you agree to comply with the aforesaid terms and conditions.</li>
                      <li> The Company reserves the right to suspend/discontinue Wallet scheme to customers at any time, for any cause, including, but not limited to, for any violation of the Terms and Conditions mentioned herein by the Wallet user or to comply with any rules, regulations, orders, directions, notifications issued by any regulatory authority.</li>
                      <li> The Company makes no express or implied warranty, guarantee, representation or undertaking whatsoever regarding the Services, which are not expressly mentioned herein.</li>
                      <li> The Company may at its sole discretion change, by addition or deletion, these Terms and Conditions.</li>
                  </ol>
              </li>
              <li> <strong>Privacy:</strong>
                  <ol>
                      <li> The 'Privacy Policy' of Website; and </li>
                      <li> The 'Cookie Policy' of Website. </li>
                  </ol>
              </li>
              <li> <strong>Links:</strong>
                  <ol>
                      <li> This Website may contain links to other websites maintained by third parties ("External Sites"). These External Sites are linked to the Website for Your reference and convenience only. digital bihar does not operate, control or endorse in any respect such External Sites or their content. You assume sole responsibility for use of these External Sites and is therefore, advised to examine the terms and conditions of those External Sites carefully.</li>
                      <li> You must not link Your own website or any third party website, to this Website without obtaining the prior written approval of digital bihar. Use of any automated screen capture or screen scraping technologies to obtain information from this Website without the prior written approval of digital bihar is an infringement of our intellectual property rights. </li>
                  </ol>
              </li>
              <li> <strong>Usage Conduct:</strong>
                  <ol>
                      <li> You acknowledge that You only have a limited right to use the Website and that You have no right to modify any part of the Website or reproduce, copy, distribute, sell, resell or access the Facility for any commercial purposes. </li>
                      <li> You are also under an obligation to use this Website for reasonable and lawful purposes only, and shall not indulge in any activity that is not envisaged in these Terms. You shall use this Website, and any bus tickets purchased through it, for personal, non-commercial use only and shall not re-sell the tickets to any other person. </li>
                      <li>You may not use any meta tags or any other hidden text utilizing the Website or its affiliates' names or trademarks without the express written consent of digital bihar and or its affiliates, as applicable. </li>
                      <li>
                          <p> You must not use the Website for any of the following: </p>
                          <ol>
                              <li> for fraudulent purposes, or in connection with any criminal acts or other unlawful activity; and/or </li>
                              <li> to send or transport in the carriage of the bus, any material that does not belong to You; or material that is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libellous, obscene, pornographic, paedophilic or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam” to cause annoyance, inconvenience or needless anxiety. </li>
                          </ol>
                      </li>
                  </ol>
              </li>
              <li> <strong>Correspondence/Notices:</strong>
                  <ol>
                      <li> When You use the Website or send emails or other data, information or communication to digital bihar, You agree and understand that You are communicating with us through electronic records and You consent to receive communications via electronic means from digital bihar periodically and as and when required.</li>
                      <li> We may communicate with You through email/SMS or by such other mode of communication, electronic or otherwise. </li>
                  </ol>
              </li>
              <li> <strong>Disclaimer of Warranties and Liability:</strong>
                  <ol>
                      <li> This Website, all the services (including but not limited to software) included on or otherwise made available to You through this Website are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing by digital bihar or on the Website. </li>
                      <li>
                          <p> Without prejudice to the forgoing paragraph, Website does not warrant that:</p>
                          <ol>
                              <li> Website will be constantly available, or available at all; or </li>
                              <li> The information on this Website is complete, true, accurate or non-misleading. </li>
                          </ol>
                      </li>
                      <li> digital bihar will not be liable to You in any way or in relation to the contents of, or use of, or otherwise in connection with, the Website. wherever, the same is under the control of the bus operator. The Website does not warrant that this Website; information, content, materials, product (including software) Facility or services included on or otherwise made available to You through the Website; the servers; or electronic communication sent from us are free of viruses or other harmful components, despite our best efforts to prevent these incidents. </li>
                      <li> You are required to enter a valid phone number while booking a bus ticket on the Website. By registering Your phone number with us, You consent to be contacted by us for the purposes of the transaction on the Website or for sending you promotional offers or content. </li>
                      <li>
                          <p> For the purpose of booking bus tickets through the Website, we warrant that we shall be responsible for the following activities:</p>
                          <ol>
                              <li> Issuing a valid ticket (a ticket that will be accepted by the bus operator); and</li>
                              <li> Providing customer support and information in case of any delays in the departure of a bus / inconvenience caused to You. </li>
                              <li> digital bihar will process the ticket cancellation request from customers subject to the cancellation and refund policy of the respective bus operator. The cancellation fee may differ for each bus operator. </li>
                          </ol>
                          <p> However, We DO NOT take any liability for the following: </p>
                          <ol>
                              <li>The bus operator's bus not departing from/reaching the pick-up point or destination on time;</li>
                              <li>The bus operator's employee/s being rude to You;</li>
                              <li>The bus operator's bus seats or the journey not being up to Your expectation;</li>
                              <li>The bus operator modifying and/or cancelling your bus ticket reservation partially or completely due to unavoidable reasons as described in the following clauses;</li>
                              <li>Your baggage getting lost/stolen/damaged;</li>
                              <li>The bus operator changing a customer's seat at the last minute to accommodate a female / child passenger;</li>
                              <li>Bus departing without You boarding the bus, while You were waiting at the wrong boarding point (please call the bus operator to find out the exact boarding point if you are not a regular traveller of a particular bus operator);</li>
                              <li>The bus operator changing the boarding point and/or using a pick-up vehicle at the boarding point to take the passengers to the bus departure point; and</li>
                              <li>The bus operator not permitting Your baggage beyond a limit determined at the bus operator’s sole discretion.</li>
                          </ol>
                      </li>
                  </ol>
              </li>
              <li> <strong>Payment:</strong>
                  <ol>
                      <li>
                          <p> By the use of any of the payment method/s available on the Website by You, digital bihar shall not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to any of the following: </p>
                          <ol>
                              <li> Lack of authorization for any transaction/s; or</li>
                              <li> Exceeding the preset limit mutually agreed by You and any bank/s; or</li>
                              <li> Any payment issues arising out of the transaction; or</li>
                              <li> Decline of transaction for any other reason/s.</li>
                          </ol>
                      </li>
                      <li>
                          <p> Please note that: </p>
                          <ol>
                              <li>Transactions, transaction price and all commercial terms governing the provision of services are bipartite contractual obligations between You and the bus operator. digital bihar acts merely as a facilitator being an independent platform and at no point in time, enters into any direct /contractual arrangement with the customers with regard to the services provided by the bus operator. Use of the payment Facility shall not render digital bihar liable or responsible for the non-delivery, non-receipt, non-payment, damage, breach of representations and warranties, or fraud as regards the services listed on the Website.</li>
                              <li>You have specifically authorized the Website or its service providers to collect, process, facilitate and remit payments and/or the transaction price electronically. Your relationship with Website is on a principal to principal basis and by accepting these Terms You agree that Website is an independent contractor for all purposes, and does not have control of or liability for the products or services that are listed on the Website that are paid for by using the payment facility. </li>
                              <li>You understand, accept and agree that the payment facility provided through any third party on the Website is neither a banking nor financial service provided by digital bihar, but is merely a facilitator providing an electronic, automated online electronic payment collection and remittance facility for the Transactions on the Website using the existing authorized banking infrastructure and credit card payment gateway networks. Further, by providing payment facility Website is neither acting as a trustee nor acting in a fiduciary capacity with respect to the transaction or the transaction price.</li>
                          </ol>
                      </li>
                  </ol>
              </li>
              <li> <strong>Cancellation &amp; Refund Policy:</strong>
                  <ol>
                      <li><strong>Cancellation policy</strong></li>
                      <p>digital bihar will process the ticket cancellation request from You as per the cancellation/refund policy of the bus operator. The cancellation fee and the period taken to process the refund will differ for each bus operator. Please refer to the bus operator's cancellation policy.</p>
                      <li><strong>How does the customer cancel a ticket?</strong></li>
                      <p>Please call on 080-3941 2345 for all cancellation related queries. Our customer support team will help you process the request as per the cancellation policy of the bus operator.</p>
                      <li><strong>Refund Policy</strong>
                          <ol>
                              <li> Customer will be entitled to a 100% refund of ticket fare if the cancellation of the journey is attributable to either digital bihar or the bus operator. Customer will not be entitled to refund for cancellation of tickets for any other reasons. </li>
                              <li> In the event of dishonour of ticket by the bus operator, a full refund of the ticket fare would be processed within seventy two (72) hours. The refund would be credited to the customer within seven (7) working days of the dishonour of ticket.</li>
                          </ol>
                      </li>
                  </ol>
              </li>
              <li> <strong>Carriage Policy:</strong>
                  <ol>
                      <li> You are responsible for ensuring that Your travel date, time and destination are correct before booking/reserving the bus tickets or when you select to confirm your ticket purchase on the Website. Please check the cancellation Policy available on the Website for details about cancellation and refunds. </li>
                      <li> You are solely responsible to be at the designated boarding point reasonably in advance before departure time. We are not liable if you fail to board the bus by the time the bus departs. </li>
                      <li>
                          <p> The bus operators reserve the right to refuse you and your luggage from carriage on the bus for whatsoever reason that they deem justified, including but not limited to: </p>
                          <ol>
                              <li>Carrying of contraband, illegal substances, fragile or oversize/overweight luggage, Your unruly behavior, drunkenness or any other behavior that the bus operator deems to affect the other passengers' comfort or safety.</li>
                              <li>You are unable to produce valid government issued identification proof while travelling.</li>
                              <li>The payment of Your fare for the ticket is fraudulent; </li>
                              <li>The booking of Your seat has been done fraudulently or unlawfully or has been purchased from a person not authorized by digital bihar;</li>
                              <li>The credit card through which your payment was made for the ticket booking has been reported lost or stolen; </li>
                              <li>The itinerary or booking or confirmation slip is counterfeit or fraudulently obtained;</li>
                              <li>The itinerary of your reservation has been altered by a person other than digital bihar or our authorized agent on your express instructions; </li>
                              <li>You are unable to produce a valid and legible boarding ticket for the intended travel. The boarding ticket constitutes as the prima facie evidence of the contract of carriage between the bus operator and the boarding ticket holder;</li>
                              <li>You are deemed medically unfit to travel and may pose a health hazard to other passengers on board the bus, at the absolute discretion of the bus operator;</li>
                              <li>You fail to arrive on time to board before the time of departure or fail to board the bus by the time the bus departs.</li>
                              <li>If the bus operator has refused to carry You or choose to remove You from carriage as per the reasons abovementioned, we reserve the right to cancel the unused ticket and You will not be entitled to further carriage or refund of fare. We will not be liable for the consequential or incidental loss, damage, cost, or fee You may incur due to the refusal of carriage.</li>
                          </ol>
                      </li>
                      <li>Children below age twelve (12) will not be allowed to book tickets for themselves nor will be allowed to travel, unless they are accompanied by an adult.</li>
                      <li>Children above the age of 5 years need to compulsorily obtain a bus ticket at the regular fare of the ticket, unless otherwise a particular bus operator specifies otherwise in their terms and conditions. </li>
                      <li>The bus operator reserve the right to reschedule, cancel, and/or delay any journey and substitute other buses for reasons they deem necessary to do so.</li>
                      <li>You are responsible to ensure that valid and necessary government issued personal identification documents, such as the passport, PAN card or Aadhar card, are carried with you for the journey.</li>
                  </ol>
              </li>
              <li> <strong>Intellectual Property Rights:</strong>
                  <ol>
                      <li>Content included on the Website, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of digital bihar, its affiliates or its content suppliers and is protected by Indian and international copyright and database right laws. </li>
                      <li>The compilation of all content on this Website is the exclusive property of Website and its affiliates and is protected by laws of India and international copyright and database right laws. All software used on this Website is the property of digital bihar, its affiliates or its software suppliers and is protected by Indian and international copyright and authors' rights laws.</li>
                      <li>You may not systematically extract/or re-utilise any parts of the contents of the Website without our express written consent. In particular, You may not utilize any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation of any substantial parts of this Website, without digital bihar's express written consent. You may also not create and/or publish Your own database that features substantial (eg: prices and service listings) parts of the Website without Rebus's express written consent.</li>
                      <li>You cannot use the digital bihar trademarks for commercially exploiting them for Your interests without our express permission. We reserve the right to initiate legal proceedings if we discover any infringement of our intellectual property rights.</li>
                  </ol>
              </li>
              <li> <strong>Grievance Officer:</strong>
                  <p> In case of any consumer grievance, the End-User may contact digital bihar on the email id provided below: </p>
                  <p> support@digital bihar.in </p>
              </li>
              <li> <strong>Indemnity:</strong>
                  <ol>
                      <li> You shall indemnify and hold harmless digital bihar, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of these Terms or any document incorporated by reference, or Your violation of any law, rules, regulations or the rights of a third party. </li>
                      <li> You hereby expressly release digital bihar or any of its affiliates or officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the vendors and specifically waiver any claims or demands that you may have in this behalf under any statute, contract or otherwise. </li>
                  </ol>
              </li>
              <li> <strong>Losses:</strong>
                  <p> digital bihar will not be responsible for any loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) and any other indirect or consequential loss to You when You commenced using the Website.</p>
              </li>
              <li> <strong>Governing law and Jurisdiction:</strong>
                  <p> These Terms are governed by and shall be construed in accordance with the laws of India. The courts in Bengaluru shall have exclusive jurisdiction in respect of any disputes arising out of or in connection with these Terms.</p>
              </li>
              <li> <strong>Suspension, Termination or Cancellation</strong>
                  <p> Website may suspend, cancel or terminate Your account registered with us, with or without prior notice, if we believe in good faith that You have breached any of these Terms or any other terms or policies referred to in these Terms. </p>
                  <p> digital bihar reserves the right, at its sole discretion, to accept, hold and/or cancel any reservation of bus tickets made by the You on the digital bihar website, digital bihar mobile website and digital bihar mobile apps, which is deemed to be fraudulent or suspicious by digital bihar.</p>
                  <p> digital bihar will endeavour to inform You in the event of cancellation of reservation, owing to fraud or suspicious activity, to the best of its capacity, but shall not be liable for a failure to communicate to You of such cancellation.</p>
              </li>
              <li> <strong>Amendment / Modification:</strong>
                  <p> digital bihar reserves the right to modify these Terms at any time with or without any further notice by uploading the revised Terms on the Website and it is Your duty to keep yourself aware of the revisions to the Terms of the Website. </p>
              </li>
              <li> <strong>Limitation Of Liability:</strong>
                  <p> THE WEBSITE/digital bihar WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, ARISING OUT OF OR IN CONNECTION WITH THE TERMS, SITE, FACILITY, TRANSACTION PROCESSING SERVICE, INABILITY TO USE THE FACILITY OR THE TRANSACTION PROCESSING SERVICE, OR THOSE RESULTING FROM ANY FACILITY PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH THE WEBSITE, BEYOND THE VALUE OF THE LAST TRANSACTION CARRIED OUT BY YOU THROUGH THE WEBSITE. </p>
              </li>
              <li> <strong>Miscellaneous:</strong>
                  <ol>
                      <li>The Parties acknowledge and accept that electronic format shall be deemed an acceptable means of communication for the purposes of these Terms.</li>
                      <li>These Terms constitute the complete and entire set of terms between the Parties on the subject of ‘terms of usage of the Website' (save and except the other policies and terms referred to in these Terms) and shall supersede any and all other prior understandings, commitments, representations or agreements, whether written or oral, between the Parties to these Terms.</li>
                      <li>If any provision of these Terms shall be found by any court or administrative body of competent jurisdiction to be invalid or unenforceable, such invalidity or enforceability shall not affect the other provisions of these Terms, which shall remain in full force and effect.</li>
                      <li>In no event will any delay, failure or omission (in whole or in part) in enforcing, exercising or pursuing any right, power, privilege, claim or remedy conferred by or arising under these Terms or by law, be deemed to be or construed as a waiver of that or any other right, so as to bar the enforcement of that, or any other right, power privilege, claim or remedy, in any other instance at any time or times subsequently.</li>
                      <p className="center-text">-------------</p>
                  </ol>
              </li>
          </ol>
          <div id="hotels">
              <h3 className="Red XCN">Hotel reservation - Terms and Conditions </h3>
              <ol>
                  <li> <strong>Scope of service:</strong>
                      <ol>
                          <li>digital bihar.in <strong>(“website/digital bihar”)</strong>provides a platform to temporary accommodation providers <strong>(“Service Providers”)</strong>to list their inventory on the website and allows you <strong>(“customer/you”)</strong>to select and reserve Accommodation, based on the customer’spersonal preferences<strong>(“Service”).</strong></li>
                          <li>The term ‘temporary accommodation’ includes but is not limited to hotels, motels, home-stays, hostels and bed &amp; breakfast (collectively <strong>“Accommodation(s)”).</strong></li>
                          <li>digital bihar acts as an intermediary between the customer and the Service Providers, that have listed their Accommodation on the website, for the purposes of reservation of such Accommodation. A reservation made through the website, istherefore a bipartite contract between the customer and the Service Provider. Therefore, the contractual terms and conditions of the Service Provider shall be applicable once areservation has been made through the website. digital bihar only undertakes to share the relevant details of the customer to the Service Provider and a confirmation email on the Service Provider’s behalf to the customer.</li>
                          <li>While rendering the Services, all the information, related to a particular Service Provider, such as the tariff, availability, facilities &amp; amenities, representative images (if any), etc.,of a particular Accommodation, displayed on the website, are attributable to the respective Service Providers themselves and they are fully responsible for updating the same. The website cannot be held liable for any discrepancy in the said information.digital bihar does not guarantee the accuracy, completeness, correctness, suitability etc., of such information to the customer and cannot be held responsible in case the information is erroneous, inaccurate, untrue, incomplete, or misleading in nature. The listing of anAccommodation on the website does not constitute and should not be regarded as a recommendation and/or an endorsement of the quality, service level, qualification or rating of any Accommodation made available, to the customer.</li>
                      </ol>
                  </li>
                  <li><strong>Pricing and tariff</strong>
                      <ol>
                          <li>Accommodation(s) may be available on other websites at tariff lower than those displayed on the website, for any specific period. However, such lower tariff offeredby the Service Provider/s could be subject to specific terms and conditions with respect to refunds, cancellations, etc. customers are advised to check the Accommodation and tariff details, Accommodation policy, booking and cancellation policy, thoroughly before making a reservation of an Accommodation.</li>
                          <li>Obvious errors and mistakes (including but not limited to misprints) are not binding.</li>
                          <li>All special offers and promotions on the website are marked as such.</li>
                      </ol>
                  </li>
                  <li><strong>General terms of use</strong>
                      <ol>
                          <li>The primary guest (if it is not the customer), must be atleast 18 years of age, to be able to check-in to an Accommodation.</li>
                          <li>Check-ins and check-outs are subject to Service Providers’ policy and terms. Customers are advised to acquaint themselves with the relevant policies before making a reservation. In case a customer is denied check-in, the website will not be responsible and/or liable for the same.</li>
                          <li>Early check-in or late check-out is subject to availability of Accommodation and the Service Provider may charge you additional tariff, subject to availability and upon Service Provider’s sole discretion. The check-in and check-out timings may change depending on seasonality and the respective Service Provider’s policies.</li>
                          <li>It is mandatory for customer to furnish photo identification at the time of check-in. According to government regulations, government issued photo identification has to be carried by every person above the age of 18 staying at an Accommodation. The identification proof include but not limited to: driving license, voter identification card, passport, or such other documents as the Service Provider may deem fit.Without a valid identification proof, the customer may not be allowed to check-in. Note – customer will note that PAN card will not be accepted as a valid identification proof.</li>
                          <li>Service Provider reserves the right of admission onto their premises. Check-ins may be denied to unmarried/unrelated couples, based on the Service Provider’s policies. Customer and his/her guests posing as a couple may be denied check-in in the absenceof adequate proof of identification, of their marriage. digital bihar will be not be responsible for denial of check-in in such instances. Therefore, customer agrees no refund can be claimed from the website, in such circumstance(s).</li>
                          <li>The reservation for stay at an Accommodation may not include additional services such as laundry, telephone facilities, meals that are not included in a particularreservation, room service etc., unless expressly stated in the respective Service Provider’s policies. The Service Providers will charge the customer for availing such additional facilities, at the time of check-out.</li>
                          <li>Service Provider may charge a mandatory meal surcharge during festive periods such as Christmas New Year's Eve or other festivals as per the policies of such Service Provider. Customer will have to settle the dues for availing any such additionalservices (including mandatory meal surcharges) with the Service Provider, at the time of check-out.</li>
                          <li>Service tax is applicable on renting of temporary Accommodation. Therefore, the Service Provider may charge the same from the customer, in addition to the tariff displayed on the website.</li>
                          <li>All the timings mentioned on the website are in Indian Standard Time, unless mentioned otherwise.</li>
                      </ol>
                  </li>
                  <li><strong>Specific terms relating to special offers, discounts etc.</strong>
                      <ol>
                          <li>digital bihar may provide, from time to time, at its sole discretion, special discount offers (“Offers”) on Accommodation reservation to its customers, that are applicable for a duration of time as provided in such Offers.</li>
                          <li>With regards the above abovementioned Offers, digital bihar reserves the right to:
                              <ol>
                                  <li>discontinue and/or extend any Offers, without assigning any reasons whatsoever, and without prior notice to the customer.</li>
                                  <li>change/ amend/ add/ delete/ modify terms and conditions of any such Offers without assigning any reasons whatsoever, without prior notice to the customer.</li>
                              </ol>
                          </li>
                          <li>Customer acknowledges that he/she will not be personally notified of any such change/ amendment / addition /deletion/ modification to the Offer.</li>
                          <li>Customer is advised to check for any such change/ amendment / addition /deletion/ modification regularly.</li>
                          <li>Customer hereby unconditionally agrees to all such changes/ amendments/ additions/deletions/ modifications.</li>
                          <li>The Offers will be applicable only on bookings made through www.digital bihar.in.</li>
                          <li>Offer discounts may vary from one Accommodation to another. Customer is advised to verify the applicable Offered on a particular Accommodation, before applying the offer code.</li>
                          <li>Offers are applicable only on the base fare of the tariff, unless stated otherwise.</li>
                          <li>One Offer cannot be combined with any other Offer(s), unless stated otherwise.</li>
                          <li>Offer is valid only for the reservations made by the customer for his/her personal use, or for reservations made for his/her family. Offer is not valid for bookings made by travel agents. digital bihar reserves the right, without prior notice to the customer, to cancel reservations, which are not made in compliance with this condition.</li>
                          <li>In addition to the general terms and conditions mentioned herein, Offers may have other terms and conditions specific to such Offer. The terms and conditions may include restrictions regarding cancellation and refund. Customer is advised to get accustomed, acknowledge and accept the same before availing any discounts under any Offers. Availing of an Offer is at the discretion of the customer.</li>
                          <li>All taxes, duties, levies and/or charges payable in connection with the benefits accruing under such special offers (if any), shall be borne solely by the customer, and digital bihar shall not be liable in any manner whatsoever for payment of any such taxes, duties, levies and/or charges.</li>
                      </ol>
                  </li>
                  <li><strong>Cancellation policy</strong>
                      <ol>
                          <li>The cancellation policy (“Cancellation Policy”) displayed on our website is very dynamic and may change in the duration between the date of making reservation and the date of customer’s stay at the Accommodation. The Cancellation Policy prevailing at the time of check-in/cancellation of the reservation by the customer will be the applicable policy.</li>
                          <li>Once a reservation is made, the customer agrees to the terms and conditions of the Service Provider, including those related to cancellation and refunds. The Service Provider may have its own cancellation policy.</li>
                          <li>The general cancellation and no-show policy of each the respective Service Provider is made available on the website on the Accommodation information page, and displayed during the time when the customer makes the reservation and may also be sent to the customer, in the email confirming the reservation.</li>
                          <li>For cancellation of reservation(s) made after availing any Offer mentioned in heading IV of these Terms, the cancellation charges are calculated on total price before the application of Offer. For such reservations, an additional cancellation charge, which will be deducted from the refund amount, after making all the deductions in accordance with the Service Provider’s cancellation policy.</li>
                          <li>For cancellation of a reservation, the customer shall make a verbal and/or a written request to our customer care representatives or make such cancellation through the website or the digital bihar mobile application.</li>
                          <li>Only those cancellation requests that are communicated through phone or via email to our customer support team, or through our website or mobile application, shall be entertained. digital bihar shall not be liable to entertain any cancellation requests made directly to the Service Provider without intimating digital bihar in writing or over the phone call.</li>
                          <li>If the customer or his/her guests do not turn up at the Accommodation (“No-Show”), pursuant to making a reservation, the customer shall continue to be liable for the entire tariff displayed at the time of making the reservation, and the Service Provider may debit the amount from the customer’s credit card directly.</li>
                      </ol>
                  </li>
                  <li><strong>Refunds &amp; modifications to reservations</strong>
                      <ol>
                          <li>digital bihar does not facilitate any changes and/or modifications to reservations once they are confirmed.</li>
                          <li>All the refunds shall be made by the Service Provider directly to the customer and digital bihar is not responsible and/or liable to facilitate any refunds.</li>
                          <li>Customer’s bank may debit convenience or such other charges, as the bank may deem appropriate, from refunds you may be entitled to, pursuant to cancellation of the reservation.</li>
                      </ol>
                  </li>
                  <li><strong>Content of Service Provider:</strong>
                      <ol>
                          <li>An authorized agent of the Service Provider may provide information about a listed Accommodation, and/or upload images of the Accommodation listed on the website (“Content”), and display such images on the website. Customers may view such images before making a reservation.</li>
                          <li>Users should keep in mind the following things while viewing the Content:
                              <ol>
                                  <li>Accommodation reviews, reports, images, videos, and any related Content which may be displayed on the website originate from third parties and represent the opinion of the respective third party, and digital bihar does not endorse, or validate or confirm the authenticity of such Content, and uses such Content at his/her own sole risk.</li>
                                  <li>Customer accepts and agrees that there could be a lapse of time between the posting, transmission, or uploading of such Content and when the customer would have viewed such Content, that the Content could be outdated.</li>
                              </ol>
                          </li>
                      </ol>
                  </li>
                  <li><strong>Customer ratings and reviews:</strong>
                      <ol>
                          <li>Users of this website may post reviews, comments and other content; send communications; and submit suggestions, comments, questions, or other information, as long as the content is not illegal, obscene, abusive, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties, or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." In the event a customer uses a false e-mail address, impersonates any person or entity, or otherwise misleads as to the origin of any content, digital bihar is entitled to delete such details, and take necessary steps.</li>
                          <li>digital bihar reserves the right (but not the obligation) to remove, refuse, delete or edit any content that in the sole judgment of digital bihar violates these Terms and Conditions, and/or terminate the customer’s permission to access or use this website.</li>
                          <li>If you do post content or submit material, and unless we indicate otherwise, you:
                              <ol>
                                  <li>(a) grant digital bihar and its affiliates a non-exclusive, royalty-free, irrevocable, perpetual and fully sub-licensable rights to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media; and</li>
                                  <li>(b) digital bihar and its affiliates and sub-licensees the right to use the name that you submit in connection with such content, if they choose.</li>
                              </ol>
                          </li>
                          <li>You agree that the rights you grant above are irrevocable during the entire period of protection of your intellectual property rights associated with such content and material. You agree to waive your right to be identified as the author of such content and your right to object to derogatory treatment of such content. You agree to perform all further acts necessary to perfect any of the above rights granted by you to digital bihar, including the execution of deeds and documents, at its request.</li>
                          <li>You represent and warrant that you own or otherwise control all of the rights to the content that you post or that you otherwise provide on or through the website; that, as at the date that the content or material is submitted to digital bihar: (i) the content and material is accurate; (ii) use of the content and material you supply does not breach any applicable digital bihar’ policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory); (iii) the content is lawful. You agree to indemnify digital bihar and its affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties.</li>
                          <li>The Accommodation star ratings are provided for your information only. The starratings are based on information we have received from our Service providers,including the Accommodations. We do not independently verify star ratings. A starrating is only indicative of the level of comfort you can expect to find in a particularAccommodation, with a higher star rating generally being indicative of a higher levelof comfort and amenities. Please be aware that star ratings can vary greatly on thebasis of location, available alternatives, local market conditions, practices or othercircumstances. Thus, it is possible that a star rating in one particular state or city isnot comparable to the same star rating in another country or city due to suchcircumstances. Star ratings do not necessarily reflect all the amenities or services thatmight be available at an Accommodation, and some amenities and features may notbe available in every room or at every property with a particular star rating. If thereare particular amenities or features that are important to you, please contact ourcustomer service and inquire as to the availability of such amenities or features.</li>
                      </ol>
                  </li>
                  <li><strong>PLEASE BE AWARE THAT BY DISPLAYING INFORMATION ABOUT ASERVICE PROVIDER, digital bihar IS NOT SUGGESTING THAT, AVAILINGTHEIR SERVICES IS ADVISABLE OR RISK FREE. digital bihar IS NOTLIABLE FOR ANY DAMAGES AND/OR LOSSES THAT MAY RESULTFROM THE CUSTOMER DECIDING TO AVAIL SUCH SERVICES. ANYSUCH RESERVATION MADE BY THE CUSTOMER IS AT THECUSTOMER’S SOLE RISK BASIS THE CUSTOMER’S INDEPENDENTJUDGEMENT.</strong></li>
              </ol>
          </div>
       </Row>
    </Grid>
    );
  }
}

export default Terms;
Terms.contextTypes = {
  router: PropTypes.object
};